### ISSUE TITLE
Nil case not handled for Optionals

### ISSUE THREAD

**Issue by k3zi** [Joannis/IkigaJSON#9]
JSONEncoder.swift doesn't seem to handle the case where the `Encodable` is an `Optional`. The result JSON outputs no value for the optional if it is nil, it instead produces invalid JSON like `{"key":}`. 

I believe this error spans across the following methods:
`mutating func encode<T>(_ value: T, forKey key: Key) throws where T : Encodable {` in `KeyedJSONEncodingContainer` since it breaks with: `{"key":}`.

`mutating func encode<T>(_ value: T) throws where T : Encodable {` in `UnkeyedJSONEncodingContainer` since it breaks with: `[0,,2,3,4]`.

~~These methods should handle the case where the value might be `nil` and adhere to the provided `encodeNilAsNull` setting, additionally not outputting the key at all if the value is `nil` and `encodeNilAsNull` is `false`.~~

I think the necessary change would be to implement `encodeIfPresent` so that the encoder can decide what to do based on `encodeNilAsNull`.

**Comment by k3zi** [comment]
I've added a pull request to fix this: #10.

**Comment by k3zi** [comment]
@Joannis 
I've submitted a pull request to fix this issue here: #10. Let me know if this is reasonable 👍

**Comment by Joannis** [comment]
Oh hey! Good that you poked me, I wasn't aware of this PR yet. Sorry!

**Comment by k3zi** [comment]
No worries! Thanks 👍
